# Generated by Django 5.2 on 2025-05-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_lesson_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
