# Generated by Django 5.2 on 2025-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
